name: mosart
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost-cpp=1.74.0=h312852a_4
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - cfitsio=3.470=hb418390_7
  - curl=7.78.0=hea6ffbf_0
  - expat=2.4.1=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - gdal=3.3.1=py38h507a4fd_1
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h4f31c25_6
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - kealib=1.4.14=hcc255d8_2
  - krb5=1.19.2=hcc1bbae_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libcurl=7.78.0=h2574ce0_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgdal=3.3.1=h8f005ca_1
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.1.0=hc902ee8_8
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=11_linux64_openblas
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - librttopo=1.1.0=h1185371_6
  - libspatialite=5.0.1=h8694cbe_5
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.2=h58526e2_4
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_1
  - pcre=8.45=h9c3ff4c_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=21.03.0=h93df280_0
  - poppler-data=0.4.10=0
  - postgresql=13.3=h2510834_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.8.10=h49503c6_1_cpython
  - python_abi=3.8=2_cp38
  - readline=8.1=h46c0cb4_0
  - setuptools=57.4.0=py38h578d9bd_0
  - sqlite=3.36.0=h9cd32fc_0
  - tiledb=2.3.3=he87e0bf_0
  - tk=8.6.11=h21135ba_0
  - tzcode=2021a=h7f98852_2
  - tzdata=2021a=he74cb21_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - affine==2.3.0
    - appdirs==1.4.4
    - arrow==1.1.1
    - attrs==21.2.0
    - backcall==0.2.0
    - black==21.7b0
    - bmipy==2.0
    - bokeh==2.3.3
    - cartopy==0.18.0
    - certifi==2021.5.30
    - cftime==1.5.0
    - chardet==4.0.0
    - click==8.0.1
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - dask==2021.6.2
    - decorator==5.0.9
    - descartes==1.1.0
    - distributed==2021.6.2
    - fiona==1.8.20
    - fsspec==2021.7.0
    - ftfy==6.0.3
    - geopandas==0.9.0
    - h5netcdf==0.11.0
    - h5py==3.4.0
    - heapdict==1.0.1
    - idna==2.10
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - locket==0.2.1
    - mailchecker==4.0.11
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - msgpack==1.0.2
    - munch==2.5.0
    - mypy-extensions==0.4.3
    - nc-time-axis==1.3.1
    - netcdf4==1.5.7
    - numba==0.53.1
    - numpy==1.21.0
    - packaging==21.0
    - pandas==1.3.0
    - parso==0.8.2
    - partd==1.2.0
    - pathspec==0.9.0
    - pathvalidate==2.4.1
    - pexpect==4.8.0
    - phonenumbers==8.12.31
    - pickleshare==0.7.5
    - pillow==8.3.1
    - proj==0.2.0
    - prompt-toolkit==3.0.20
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pyarrow==4.0.1
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyproj==3.1.0
    - pyshp==2.1.3
    - python-benedict==0.24.0
    - python-dateutil==2.8.2
    - python-fsutil==0.5.0
    - python-slugify==5.0.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - rasterio==1.2.6
    - regex==2021.7.6
    - requests==2.25.1
    - richdem==0.3.4
    - rioxarray==0.5.0
    - scipy==1.7.1
    - shapely==1.7.1
    - six==1.16.0
    - snuggs==1.4.7
    - sortedcontainers==2.4.0
    - tblib==1.7.0
    - text-unidecode==1.3
    - toml==0.10.2
    - tomli==1.2.1
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.61.2
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - xarray==0.18.2
    - xmltodict==0.12.0
    - zict==2.0.0
prefix: /home/sm510/anaconda3/envs/mosart
